Controllers/ReportController.cs
using System.IO;
using System.Security.Cryptography;
using System;
using System.Web.Mvc;
using SBM_POWER_BI.Classes;
using System.Linq;
using SBM_POWER_BI.Models;
using System.Web;
using System.Reflection;

namespace SBM_POWER_BI.Controllers
{
    [JwtAuthorize]
    public class ReportController : Controller
    {
        readonly JwtTokenGenerator JWT = new JwtTokenGenerator();
        readonly MasterDataController MD = new MasterDataController();

        public ActionResult Dashboard()
        {
            try
            {
                GetCookies();
                return View();
            }
            catch (Exception)
            {
                return View("Index", "Error");
            }
        }

        public ActionResult DashboardList()
        {
            try
            {
                GetCookies();
                return View();
            }
            catch (Exception)
            {
                return View("Index", "Error");
            }
        }

        public ActionResult Item()
        {
            try
            {
                GetCookies();
                return View();
            }
            catch (Exception)
            {
                return View("Index", "Error");
            }
        }

        public ActionResult Detail()
        {
            try
            {
                GetCookies();
                ViewBag.REPORT_URL = COOKIES.GetCookies("REPORT_URL");
                return View();
            }
            catch (Exception)
            {
                return View("Index", "Error");
            }
        }

        public void GetCookies()
        {
            ViewBag.USERID = COOKIES.GetCookies("USERID") ?? "";
            ViewBag.WINDOWSID = COOKIES.GetCookies("WINDOWSID") ?? "";
            ViewBag.NAME = COOKIES.GetCookies("NAME") ?? "";
            ViewBag.EMAIL = COOKIES.GetCookies("EMAIL") ?? "";
            ViewBag.DEPARTMENT = COOKIES.GetCookies("DEPARTMENT") ?? "";
            ViewBag.GROUPS_MDM = COOKIES.GetCookies("GROUPS_MDM") ?? "";
            ViewBag.GROUPS_PBI = COOKIES.GetCookies("GROUPS_PBI") ?? "";
            ViewBag.INITIALS = COOKIES.GetCookies("INITIALS") ?? "";

            Assembly assembly = Assembly.GetExecutingAssembly();
            string versions = assembly.GetCustomAttribute<AssemblyFileVersionAttribute>()?.Version ?? "Unknown";
            string appNames = assembly.GetCustomAttribute<AssemblyProductAttribute>()?.Product ?? "Unknown";
            string companys = assembly.GetCustomAttribute<AssemblyCompanyAttribute>()?.Company ?? "Unknown";
            var BT = System.IO.File.GetLastWriteTime(Assembly.GetExecutingAssembly().Location);
            string BUILDTIME = BT.ToString("dd MMM yyyy HH:mm:ss tt").ToUpper();
            string headers = $"{appNames} © {DateTime.Now.Year} {companys}";

            ViewBag.BUILDTIME = BUILDTIME;
            ViewBag.INFO = headers;
            ViewBag.APPNAME = appNames;
            ViewBag.VERSION = versions;
            ViewBag.COMPANY = companys;
        }

        public ActionResult Shared(string ID)
        {
            MASTERDATA MD = new MASTERDATA();
            var URL_TYPE = "0";
            var USER_ID = GetUserIpAddress();
            System.Net.IPHostEntry entry = System.Net.Dns.GetHostEntry(USER_ID);
            string MACHINE = entry.HostName.ToUpper() + " (" + (COOKIES.GetCookies("NAME") ?? "COOKIES EXPIRE") + ")";
            //System.Net.IPHostEntry entry = System.Net.Dns.GetHostEntry(USER_ID);
            //clientMachineName = entry.HostName;
            var res1 = MD.GET_PBI_SHARE_URL(URL_TYPE, HttpUtility.UrlEncode(ID), "");
            if(res1[0].REPORT_ID != "")
            {
                var REPORT_ID = Decrypt(ID, res1[0].REPORT_ID);
                PBI_REPORT MODEL = new PBI_REPORT
                {
                    ID = REPORT_ID,
                };

                var res2 = MD.UPDATE_TOTAL_VIEW(MODEL, res1[0].URL_TYPE);
                MD.LOG_URL(res1[0].REPORT_ID, USER_ID, MACHINE);
                ViewBag.REPORT_URL = res2.Message.ToString();
                return View();
            }
            else
            {
                return RedirectToAction("Index","Error");
            }
        }


        [AllowAnonymous]
        public ActionResult SharedTV(string ID)
        {
            MASTERDATA MD = new MASTERDATA();
            var URL_TYPE = "1";
            var USER_ID = GetUserIpAddress();
            System.Net.IPHostEntry entry = System.Net.Dns.GetHostEntry(USER_ID);
            string MACHINE = entry.HostName.ToUpper() + " (" + (COOKIES.GetCookies("NAME") ?? "COOKIES EXPIRE") + ")";
            var res1 = MD.GET_PBI_SHARE_URL(URL_TYPE, HttpUtility.UrlEncode(ID), "");
            var REPORT_ID = Decrypt(ID, res1[0].REPORT_ID);
            PBI_REPORT MODEL = new PBI_REPORT
            {
                ID = REPORT_ID,
            };
            COOKIES.PostCookies("URL_TYPE", res1[0].URL_TYPE);
            var res2 = MD.UPDATE_TOTAL_VIEW(MODEL, res1[0].URL_TYPE);
            MD.LOG_URL(res1[0].REPORT_ID, USER_ID, MACHINE);
            ViewBag.REPORT_ID = REPORT_ID;
            ViewBag.REPORT_URL = res2.Message.ToString();
            return View();
        }

        [AllowAnonymous]
        public JsonResult LOAD_FRAME(PBI_REPORT MODEL)
        {
            try
            {
                MASTERDATA MD = new MASTERDATA();
                var URL_TYPE  = COOKIES.GetCookies("URL_TYPE");
                var res = MD.UPDATE_TOTAL_VIEW_NEW(MODEL, URL_TYPE);
                return Json(new { res }, JsonRequestBehavior.AllowGet);
            }
            catch (Exception ex)
            {
                return Json(new
                {
                    Result = false,
                    StatusCode = ((HttpException)ex).GetHttpCode(),
                    Message = ex.Message.ToString(),
                    Data = "",
                }, JsonRequestBehavior.AllowGet);
            }
        }


        private string GetUserIpAddress()
        {
            string ipAddress = HttpContext.Request.UserHostAddress;
            if (string.IsNullOrEmpty(ipAddress) || ipAddress.ToLower() == "unknown")
            {
                string forwardedFor = HttpContext.Request.ServerVariables["HTTP_X_FORWARDED_FOR"];
                if (!string.IsNullOrEmpty(forwardedFor))
                {
                    string[] forwardedIps = forwardedFor.Split(',');
                    if (forwardedIps.Length > 0)
                    {
                        ipAddress = forwardedIps[0].Trim();
                    }
                }
            }
            if (string.IsNullOrEmpty(ipAddress) || ipAddress.ToLower() == "unknown")
            {
                ipAddress = HttpContext.Request.ServerVariables["REMOTE_ADDR"];
            }
            return ipAddress;
        }

        public static string Encrypt(string plainText, string key)
        {
            using (Aes aesAlg = Aes.Create())
            {
                aesAlg.Key = Convert.FromBase64String(key);
                aesAlg.GenerateIV();
                ICryptoTransform encryptor = aesAlg.CreateEncryptor(aesAlg.Key, aesAlg.IV);
                using (MemoryStream msEncrypt = new MemoryStream())
                {
                    using (CryptoStream csEncrypt = new CryptoStream(msEncrypt, encryptor, CryptoStreamMode.Write))
                    {
                        using (StreamWriter swEncrypt = new StreamWriter(csEncrypt))
                        {
                            swEncrypt.Write(plainText);
                        }
                    }
                    byte[] encryptedDataWithIV = aesAlg.IV.Concat(msEncrypt.ToArray()).ToArray();
                    return Convert.ToBase64String(encryptedDataWithIV);
                }
            }
        }

        public static string Decrypt(string cipherText, string key)
        {
            using (Aes aesAlg = Aes.Create())
            {
                aesAlg.Key = Convert.FromBase64String(key);
                byte[] iv = new byte[aesAlg.BlockSize / 8];
                byte[] encryptedData = Convert.FromBase64String(cipherText);
                Array.Copy(encryptedData, iv, iv.Length);
                aesAlg.IV = iv;

                ICryptoTransform decryptor = aesAlg.CreateDecryptor(aesAlg.Key, aesAlg.IV);

                using (MemoryStream msDecrypt = new MemoryStream(encryptedData, iv.Length, encryptedData.Length - iv.Length))
                {
                    using (CryptoStream csDecrypt = new CryptoStream(msDecrypt, decryptor, CryptoStreamMode.Read))
                    {
                        using (StreamReader srDecrypt = new StreamReader(csDecrypt))
                        {
                            return srDecrypt.ReadToEnd();
                        }
                    }
                }
            }
        }
    }
}

Views/Report/DashboardList.cshtml
@{
    Layout = "~/Views/Shared/AspStudio/_Layout.cshtml";
    ViewBag.Title = "Dashboard";
}
<div class="d-flex align-items-center mb-3">
    <div>
        <h1 class="page-header mb-0">Dashboard</h1>
    </div>
    <div class="ms-auto">
        <div class="btn-group ms-md-4 mt-md-0 mt-2">
            <button type="button" class="btn btn-theme dropdown-toggle" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                <i class="fa fa-exchange-alt fa-fw me-1"></i> Change View
            </button>
            <div class="dropdown-menu">
                <a class="dropdown-item" href="#" onclick="GOTO_GRID()">Grid</a>
                <a class="dropdown-item" href="#" onclick="GOTO_LIST()">List <i class="fa fa-check fa-fw me-1"></i></a>
            </div>
        </div>
    </div>
</div>
<div class="card">
    <ul class="nav nav-tabs nav-tabs-v2 px-4">
        <li class="nav-item me-3"><a href="#allTab" class="nav-link active px-2" data-bs-toggle="tab">All Reports</a></li>
        <li class="nav-item me-3"><a href="#publishedTab" class="nav-link px-2" data-bs-toggle="tab"> Recent Add</a></li>
        <li class="nav-item me-3"><a href="#expiredTab" class="nav-link px-2" data-bs-toggle="tab">Recent View</a></li>
    </ul>
    <div class="tab-content p-4">
        <div class="tab-pane fade show active" id="allTab">
            <div class="table-responsive">
                <table class="table table-hover text-nowrap" id="table_1">
                    <thead>
                        <tr>
                            <th class="border-top-0 pt-0 pb-2"></th>
                            <th class="border-top-0 pt-0 pb-2">Report Name</th>
                            <th class="border-top-0 pt-0 pb-2">Report Description</th>
                            <th class="border-top-0 pt-0 pb-2">Report Department</th>
                            <th class="border-top-0 pt-0 pb-2">Report Category</th>
                            <th class="border-top-0 pt-0 pb-2">Total Views</th>
                            <th class="border-top-0 pt-0 pb-2">Create Date</th>
                            <th class="border-top-0 pt-0 pb-2">Update Date</th>
                        </tr>
                    </thead>
                    <tbody>
                    </tbody>
                </table>
            </div>
        </div>
    </div>

</div>
<script>
    $(document).ready(function () {
        GET_REPORT();
    });
    function GOTO_GRID() {
         window.location.href = '@Url.Action("Dashboard", "Report")';
    }
    function GOTO_LIST() {
        window.location.href = '@Url.Action("DashboardList", "Report")';
    }
    function GET_REPORT() {
        var URL = "@Url.Action("GET_REPORT", "MASTERDATA")";
        var option = "";
        option = {
            "destroy": true,
            "searching": true,
            "paging": true,
            "filter": true,
            "responsive": false,
            "scrollX": true,
            "lengthMenu": [10, 20, 30, 40, 50, 100, 200, 500, 1000],
            "pageLength": 20,
            "dom": "<'row mb-3'<'col-md-4 mb-3 mb-md-0'l><'col-md-8 text-right'<'d-flex justify-content-end'f<'ms-2'B>>>>t<'row align-items-center'<'mr-auto col-md-6 mb-3 mb-md-0 mt-n2 'i><'mb-0 col-md-6'p>>",
            "buttons": [
                {
                    text: '<i class="fa fa-plus"></i>',
                    className: 'btn btn-default',
                    action: function (e, dt, node, config) {
                        ADD();
                    }
                },
                {
                    extend: 'print',
                    className: 'btn btn-default',
                    text: '<i class="fa fa-print"></i>',
                    exportOptions: {
                        columns: ':visible'
                    }
                },
                {
                    extend: 'copy',
                    className: 'btn btn-default',
                    text: '<i class="fa fa-copy"></i>',
                    exportOptions: {
                        columns: ':visible'
                    }
                },
                {
                    extend: 'csv',
                    className: 'btn btn-default',
                    text: '<i class="fa fa-file-excel"></i>',
                    exportOptions: {
                        columns: ':visible'
                    }
                },
                {
                    extend: 'colvis',
                    className: 'btn btn-default',
                    text: '<i class="fa fa-eye"></i>',
                    exportOptions: {
                        columns: ':visible'
                    }
                }
            ],
            "oLanguage": {
                "oPaginate": {
                    "first": "First",
                    "last": "Last",
                    "next": "Next",
                    "previous": "Prev"
                },
                "sInfo": "_START_ -_END_ of _TOTAL_",
                "infoEmpty": "0",
                "infoFiltered": "( Total _MAX_  )",
                "sSearch": "",
                "sSearchPlaceholder": "Type in to Search",
                "sLengthMenu": "<span class='d-none d-sm-inline-block'>Show</span><div class='form-control-select'> _MENU_ </div>",
            },
            "ajax": {
                "url": URL,
                "type": "GET",
                "datatype": "json",
                "lengthMenu": [[10, 25, 50, -1], [10, 25, 50, "All"]],
                "data": function(a) {
                    return $.extend({}, a, {
                    });
                }
            },
            "columns": [
                {
                    "render": function (data, type, full, meta) {
                        var EDIT_BTN = '';
                        EDIT_BTN = '<span onclick="UPDATE_TOTAL_VIEW(\'' + full.ID + '\')" class="badge bg-teal text-teal-800 bg-opacity-25 px-2 pt-5px pb-5px rounded fs-12px d-inline-flex align-items-center"><i class="fa fa-eye text-teal fs-9px fa-fw me-5px"></i>VIEW</span>'
                        return EDIT_BTN
                    }
                },
                { data: 'REPORT_NAME', width: '200px' },
                { data: 'REPORT_DESC', width: '300px' },
                { data: 'REPORT_DEPT', width: '200px' },
                {
                    "render": function (data, type, full, meta) {
                        var RTN = ''
                        if (full.REPORT_CATEGORY === 'PRODUCTION') {
                            RTN = '<span class="badge bg-teal text-teal-800 bg-opacity-25 px-2 pt-5px pb-5px rounded fs-12px d-inline-flex align-items-center"><i class="fa fa-circle text-teal fs-9px fa-fw me-5px"></i>' + full.REPORT_CATEGORY + '</span>'
                        }
                        else if (full.REPORT_CATEGORY === 'PILOT') {
                            RTN = '<<span class="badge bg-yellow bg-opacity-50 text-black text-opacity-50 px-2 pt-5px pb-5px rounded fs-12px d-inline-flex align-items-center"><i class="fa fa-circle fs-9px fa-fw me-5px"></i>' + full.REPORT_CATEGORY + '</span>'
                        }
                        else {
                            RTN = '<span class="badge bg-gray-100 text-black text-opacity-50 px-2 pt-5px pb-5px rounded fs-12px d-inline-flex align-items-center"><i class="fa fa-circle text-gray-500 fs-9px fa-fw me-5px"></i>' + full.REPORT_CATEGORY + '</span>'
                        }

                        return RTN;
                    }
                },
                { data: 'TOTAL_VIEW',  width: '100px' },
                { data: 'CREATE_DATE', width: '100px' },
                { data: 'UPDATE_DATE', width: '100px' },
            ]
        };
        table = $("#table_1").DataTable(option);
    }
    function UPDATE_TOTAL_VIEW(ID) {
        var URL = "@Url.Action("UPDATE_TOTAL_VIEW", "MASTERDATA")";
        var MODEL = {
            ID: ID
        };
        $.ajax({
            type: "POST",
            url: URL,
            data: '{MODEL: ' + JSON.stringify(MODEL) + '}',
            contentType: "application/json; charset=utf-8",
            dataType: "json",
            success: function (data) {
                if (data.res.Message !== '') {
                    window.open('@Url.Action("Detail", "Report")', '_blank');
                }
            },
            error: {
                function(request, status, error) {
                    LOADING_HIDE();
                    ShowError("UPDATE_TOTAL_VIEW", request.responseText);
                }
            }
        });
    }

</script>

Views/Report/Detail.cshtml
@{
    Layout = "~/Views/Shared/AspStudio/_Layout_Detail_New.cshtml";
    ViewBag.Title = "Detail";
}
<!-- Add this in your HTML -->


<style>
    body {
        margin: 0;
    }

    iframe {
        display: block;
        background: #ffffff;
        border: none;
        height: calc(100vh - 3.75rem);
        width: 100%;
    }
</style>
<style type="text/css" media="print">
        body {
            visibility: hidden;
            display: none
        }
    </style>
<iframe id="iframepowerbi" sandbox="allow-same-origin allow-scripts allow-forms allow-popups" src="@ViewBag.REPORT_URL"></iframe>


<script>
    $(document).ready(function () {
        //HIDE();

    });
    function HIDE() {
        window.open('CallPBI:0');
    }

    function SHOW() {
        window.open('CallPBI:1');
    }
</script>

Views/Report/Shared.cshtml
@{
    Layout = "~/Views/Shared/AspStudio/_Layout_Detail_New.cshtml";
    ViewBag.Title = "Shared";
}
<!-- Add this in your HTML -->


<style>
    body {
        margin: 0;
    }
    iframe {
        display: block;
        background: #ffffff;
        border: none;
        height: calc(100vh - 3.75rem);
        width: 100%;
    }
</style>
<style>
    @@media print {
        @@page {
            size: A3 landscape; /* Set the paper size to A4 in landscape orientation */
            margin: 0; /* Set all margins to zero */
            n-up: 2; /* Set two pages per sheet */
        }
    }
</style>

<iframe id="iframepowerbi" sandbox="allow-same-origin allow-scripts allow-forms allow-popups" src="@ViewBag.REPORT_URL" onload="iframeLoaded()"></iframe>

<script>

    function iframeLoaded() {
        GET_PERMISSION("VIEW", function (success) {
            if (success === "True") {
                
            } else {
                var iframeToRemove = document.getElementById("iframepowerbi");
                if (iframeToRemove) {
                    iframeToRemove.remove();
                }
                alert("Forbidden action.")
            }
            //HIDE();
        });
    }
    function HIDE() {
        window.open('CallPBI:0');
    }
    function SHOW() {
        window.open('CallPBI:1');
    }
    @*function GET_PERMISSION(TYPE, callback) {
        var URL = "@Url.Action("GET_PERMISSION", "MASTERDATA")";
        $.ajax({
            type: "POST",
            url: URL,
            contentType: "application/json; charset=utf-8",
            dataType: "json",
            success: function (data) {
                var CREATE = data.res[0].ALLOW_CREATE;
                var EXPORT = data.res[0].ALLOW_EXPORT;
                var SHARE = data.res[0].ALLOW_SHARE;
                var VIEW = data.res[0].ALLOW_VIEW;
                if (TYPE == "CREATE") {
                    callback(CREATE);
                }
                else if (TYPE == "EXPORT") {
                    callback(EXPORT);
                }
                else if (TYPE == "SHARE") {
                    callback(SHARE);
                }
                else if (TYPE == "VIEW") {
                    callback(VIEW);
                }
                else {
                    callback(false);
                }
            },
            error: function (request, status, error) {
                callback(false);
            }
        });
    }*@
</script>

Views/Report/SharedTV.cshtml
@{
    Layout = "~/Views/Shared/AspStudio/_Layout_Detail_New_TV.cshtml";
    ViewBag.Title = "Shared TV";
}
<!-- Add this in your HTML -->


<style>
    body {
        margin: 0;
    }
    iframe {
        display: block;
        background: #ffffff;
        border: none;
        height: calc(100vh - 3.75rem);
        width: 100%;
    }
</style>

<div id="carousel">
    <div class="card">
        <div class="card-body" style="padding: 0px">
            <div id="carouselExample" class="carousel slide" data-ride="carousel">
                <ol class="carousel-indicators">

                </ol>
                <div class="carousel-inner">

                </div>
            </div>
        </div>
    </div>
</div>

<script>

    $(document).ready(function () {
        //HIDE();
        LOAD_FRAME();
    });

    function LOAD_FRAME() {
        var URL = "@Url.Action("LOAD_FRAME", "REPORT")";
        var MODEL = {
            ID: '@ViewBag.REPORT_ID'
        };
        $.ajax({
            type: "POST",
            url: URL,
            data: JSON.stringify({ MODEL: MODEL }),
            contentType: "application/json; charset=utf-8",
            dataType: "json",
            success: function (data) {
                var iframeUrls = [];
                for (let i = 0; i < data.res.length; i++) {
                    iframeUrls.push(data.res[i].REPORT_URL);
                }
                var carouselIndicators = $('.carousel-indicators');
                var carouselInner = $('.carousel-inner');
                for (var i = 0; i < iframeUrls.length; i++) {
                    carouselIndicators.append('<li data-bs-target="#carouselExample" data-bs-slide-to="' + i + '" ' + (i === 0 ? 'class="active"' : '') + '></li>');
                    carouselInner.append('<div class="carousel-item ' + (i === 0 ? 'active' : '') + '">'
                        + '<iframe id=iframepowerbi sandbox="allow-same-origin allow-scripts allow-forms allow-popups" src="' + iframeUrls[i] + '" alt="" class="d-block w-100"></iframe>'
                        + '</div>');
                }
                setInterval(clickNextButton, 30000);
            },
            error: function (request, status, error) {

            }
        });
    }

    function clickNextButton() {
        var nextButton = document.getElementById('btn_next');
        if (nextButton) {
            nextButton.click();
        }
    }

    function HIDE() {
        window.open('CallPBI:0');
    }

    function SHOW() {
        window.open('CallPBI:1');
    }

</script>